// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xex_1layer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEx_1layer_CfgInitialize(XEx_1layer *InstancePtr, XEx_1layer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif
void XEx_1layer_Start(XEx_1layer *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEx_1layer_IsDone(XEx_1layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEx_1layer_IsIdle(XEx_1layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEx_1layer_IsReady(XEx_1layer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEx_1layer_EnableAutoRestart(XEx_1layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XEx_1layer_DisableAutoRestart(XEx_1layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XEx_1layer_InterruptGlobalEnable(XEx_1layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_GIE, 1);
}

void XEx_1layer_InterruptGlobalDisable(XEx_1layer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_GIE, 0);
}

void XEx_1layer_InterruptEnable(XEx_1layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_IER);
    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XEx_1layer_InterruptDisable(XEx_1layer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_IER);
    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XEx_1layer_InterruptClear(XEx_1layer *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEx_1layer_WriteReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XEx_1layer_InterruptGetEnabled(XEx_1layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_IER);
}

u32 XEx_1layer_InterruptGetStatus(XEx_1layer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEx_1layer_ReadReg(InstancePtr->Control_bus_BaseAddress, XEX_1LAYER_CONTROL_BUS_ADDR_ISR);
}

